/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
        public String getGreeting() {
              return "hello bit";
      }
    public static void main(String[] args) {
        System.out.println("hello bit");
    }
}
